---
title: "Assignment 02"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

**Out: 03/18 19:00 **  
**Due: 04/01 19:00 **  

***

# Instructions  

**Collaboration:**  

Collaboration on solving the assignment is allowed, after you have thought about the problem sets on your own. It is also OK to get clarification (but not solutions) from online resources, again after you have thought about the problem sets on your own. There are two requirements: 

* Cite your collaborators **fully and completely** (*e.g.*, "XXX explained to me what is asked in problem set 3"). Or cite online resources (*e.g.*, "I got inspired by reading XXX") that helped you.

* Write your scripts and report **independently** - the scripts and report must come from you only.

**Submitting your assignment:**  

Submit your R scripts and report to TA (12332275@mail.sustech.edu.cn)

**Late Submission:**   

Late submissions will not receive any credit. 

***

# 1. Solving problems

**1.1 [10 points]** [RS], p53, Exercise #15. 

***

# 2. North America rivers

Load `rivers` data sets (length of `141` rivers in North America) by calling `data(rivers)`

**2.1 [15 points]** Make a density plot, a Q-Q plot, and a box plot; 

**2.2 [10 points]** Is the sample from a normal distribution? If not, can you make a normal transformation for the sample?

***

# 3. Beaver body temperatures

Load `beaver1` and `beaver2` data sets (body temperature data of two beavers every 10 minutes) by calling `data(beavers)`

**3.1 [5 points]** Visualize body temperature of the two beavers in multiple ways

**3.2 [5 points]** Check the normality of the two samples

**3.3 [5 points]** We need to check whether the body temperatures of the two beavers are the same. How to write H0 and H1 then? Can H0 and H1 be exchanged? 

**3.4 [5 points]** Do you use a Z-test or a t-test? Report your findings.
