---
title: "Assignment 03"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

**Out: 03/31 19:00 **  
**Due: 04/14 19:00 **  

***

# Instructions  

**Collaboration:**  

Collaboration on solving the assignment is allowed, after you have thought about the problem sets on your own. It is also OK to get clarification (but not solutions) from online resources, again after you have thought about the problem sets on your own. There are two requirements: 

* Cite your collaborators **fully and completely** (*e.g.*, "XXX explained to me what is asked in problem set 3"). Or cite online resources (*e.g.*, "I got inspired by reading XXX") that helped you.

* Write your scripts and report **independently** - the scripts and report must come from you only.

**Submitting your assignment:**  

Submit your R scripts and report to TA (12431312@mail.sustech.edu.cn)

**Late Submission:**   

Late submissions will not receive any credit. 

***

**Hint:** Please follow the general steps of hypothesis testing as introduced in the lecture.

***

# 1. Bumpus Natural Selection 

[RS], p54, Exercise #21. **[15 points]**

***

# 2.  Brain Size and Litter Size

[RS], p83, Exercise #33. **[15 points]**

***

# 3.  Was Tyrannosaurus Rex Warm-Blooded? 

[RS], p146, Exercise #23. **[15 points]**

***

# 4. Vegetarians and Zinc 

Previous studies suggest that vegetarians may not receive enough zinc in their diets. As the zinc requirement is particularly important during the pregnancy, researchers conducted a study to determine whether vegatarian pregnant women are at greater risk from zinc level than are nonvegetarian pregnant women. 

`23` women were monitored: `12` vegetarians who were pregnant, `6` nonvegetarian who were pregnant, and 5 vegetarians who were not pregnant. None of these women was smokers, and none of the nonpregnant women was taking oral contraceptives. The zinc status in each woman was measured by zinc content in the blood, urine, and hair. The following table presents zinc levels in the hair. (Source: King et al., Effect of vegetarianism on the Zinc Status of Pregnant Women, *American Journal of Clinical Nutrition*, 34(108), 1049-1055.)

|Pregnant nonvegetarians|Pregnant vegetarians|Nonpregnant vegetarians|
|:---|:---|:---|
|185|171|210|
|189|174|139|
|187|202|172|
|181|171|198|
|150|207|177|
|176|125||
||189||
||179||
||163||
||174||
||184||
||186||

**[15 points]** What evidence is there that pregnant vegetarians tend to have lower zinc levels than pregnant nonvegetarians?
