---
title: "Assignment 04"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

**Out: 04/11 10:20 **  
**Due: 04/25 10:20 **  

***

# Instructions  

**Collaboration:**  

Collaboration on solving the assignment is allowed, after you have thought about the problem sets on your own. It is also OK to get clarification (but not solutions) from online resources, again after you have thought about the problem sets on your own. There are two requirements: 

* Cite your collaborators **fully and completely** (*e.g.*, "XXX explained to me what is asked in problem set 3"). Or cite online resources (*e.g.*, "I got inspired by reading XXX") that helped you.

* Write your scripts and report **independently** - the scripts and report must come from you only.

**Submitting your assignment:**  

Submit your R scripts and report to TA (12132243@mail.sustech.edu.cn)

**Late Submission:**   

Late submissions will not receive any credit. 

***

**Hint:** Please follow the general steps of hypothesis testing as introduced in the lecture.

***

# 1. Is the dice fair?

Toss a dice `300` times repeatedly, frequency of number `1` to `6`  is as follows：

`40, 70, 48, 60, 52, 30`

**[10 points]** Based on the observations, is this a fair dice? 

***

# 2. Aerosol surface density and Pb content

An experiment is conducted to study the relationship between aerosol surface density (m^-1^) and Pb content. The observations are as fellow:

+ Surface density: `8.7, 8.5, 9.1, 9.3, 6.3, 7.8, 9.9, 6.5, 6.6, 9.5, 9.4, 7.2, 8.6, 9.6, 11.1`

+ Pb content: `6.0, 5.7, 6.0, 5.7, 4.7, 5.5, 6.4, 4.2, 6.2, 5.9, 5.7, 5.7, 6.1, 6.3, 6.0`

**[10 points]** Does aerosol surface density relate to Pb content? Report your results. 

***

# 3. Noise and blood pressure

Exposure to a consistent level of noise may increase human's blood pressure. To test this, blood pressures are measured for `12` volunteers before and after noise exposure.

+ Before: `134, 112, 113, 113, 111, 153, 143, 105, 142, 157, 119, 111`

+ After: `132, 126, 149, 124, 118, 157, 142, 124, 139, 157, 135, 125`

**[10 points]** Do the observations support the hypothesis? Report your results. 

***

# 4. Antibiotics and plasma protein binding

Injecting antibiotics causes the phenomenon of antibiotics and plasma protein binding, which will reduce the efficacy of the drug. 

The following is a list of the percentage of antibiotics bound to plasma proteins when `5` antibiotics are injected into cattle:

|Penicillin|Tetracycline|Streptomycin|Erythromycin|Chloramphenicol|
|:---------|:-----------|:-----------|:-----------|:--------------|
|29.6      |27.3        |5.8         |19.0        |29.2           | 
|24.3      |32.6        |6.2         |18.3        |32.8           | 
|28.5      |30.8        |11.0        |17.4        |25.0           | 
|32.0      |34.8        |8.3         |21.6        |24.2           |

**[5 points] 4.1** Are there any significant differences in the percentage of the five antibiotics bound to plasma proteins? 

**[5 points] 4.2** Calculate the `95%` confidence interval of the average of the percentage of `5` antibiotics bound to plasma protein.

**[5 points] 4.3** Find the `95%` confidence interval of the mean difference between penicillin and streptomycin.

***

# 5. Atmospheric lapse rate 

The *lapse rate* is the rate at which temperature drops as you increase elevation. Some hardy students were interested in checking empirically if the lapse rate of `9.8` degrees C km^-1^ was accurate for their hiking. 

To investigate, they grabbed their thermometers and their Huawei wrist altimeters and found the following data on their hike.

||1|2|3|4|5|6|7|8|
|---:|---:|---:|---:|---:|---:|---:|---:|---:|
|Elevation (m)|180|305|381|488|549|640|762|883|
|Temperature (degrees C)|13.3|12.2|13.3|10.0|8.3|9.4|8.3|7.2|

**[15 points]** Draw a scatter plot with regression line, and investigate if the lapse rate is `9.8` degrees C km^-1^.
