---
title: "Section 21 Wrapping up"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

***

# More on plotting 

## The `lattice` package

* The `lattice` package. The `lattice` package is a powerful and elegant data **visualization system** that aims to improve on base R graphs. `Lattice` is simliar to `ggplot2` in a way that they both plot using a grammar-ish syntax. Here are some good resource:

* [R Lattice Package | A must-learn concept for all R programmers](https://data-flair.training/blogs/r-lattice-package/)

* [Lattice plotting environment](https://mgimond.github.io/ES218/Week04b.html)


## The R Graph Gallery

[The R Graph Gallery](https://www.r-graph-gallery.com/index.html) is a collection of charts made with R. The gallery provides hundreds of charts, with their **reproducible code** available. This should be your go-to website if you know what plot you want to make but don't know how to make it with R. 


## Data Visualization with R

[Data Visualization with R](https://rkabacoff.github.io/datavis/) by Rob Kabacoff is a **comprehensive manual** for making publication-ready graphs. You can find pretty much every type of plots and know how to make it with `ggplot2`.


***

# Key points summary

On board.


