---
title: "Schedule"
---
**Class Time:**   
Monday 19:00-21:00  
Wednesday (odd week only) 19:00-21:00   

**Location:**   
108, Business School  

**2024 Spring:**

Section|Week|Date |Day  | Topic                                                                                      | Pre-class readings | Assignment                                                   |
|:----:|:--:|:---:|:---:|:-------------------------------------------------------------------------------------------|:------------------:|:------------------------------------------------------------:|
|01    |1   |02/19|M.   |[Introduction and `R` tutorial](https://zhu-group.github.io/ese335/S01.html)                |                    |                                                              |
|02    |2   |02/26|M.   |[Data wrangling and quick plots](https://zhu-group.github.io/ese335/S02.html)               |                    |                                                              |
|03    |2   |02/28|W.   |[Review of statistic basics (I)](https://zhu-group.github.io/ese335/S03.html)               | [RS] p1-22         |                                                              |
|04    |3   |03/04|M.   |[Review of statistic basics (II)](https://zhu-group.github.io/ese335/S04.html)              | [RS] p1-22         | [Assignment 01](https://zhu-group.github.io/ese335/A01.html) |
|05    |4   |03/11|M.   |[Normal distribution](https://zhu-group.github.io/ese335/S05.html)                          |                    |                                                              |
|06    |4   |03/13|W.   |[One-sample Z-test and t-test](https://zhu-group.github.io/ese335/S06.html)                 | [RS] p28-51        |                                                              |
|07    |5   |03/18|M.   |[Two-sample Z-test and t-test](https://zhu-group.github.io/ese335/S07.html)                 | [RS] p28-51        | [Assignment 02](https://zhu-group.github.io/ese335/A02.html) |   
|08    |6   |03/25|M.   |[Paired sample t-test and confidence interval](https://zhu-group.github.io/ese335/S08.html) |                    |                                                              |
|09    |6   |03/27|W.   |[Assumptions for t tests](https://zhu-group.github.io/ese335/S09.html)                      | [RS] p58-106       |                                                              |
|10    |7   |04/01|M.   |[One-way ANOVA](https://zhu-group.github.io/ese335/S10.html)                                | [RS] p113-140      | [Assignment 03](https://zhu-group.github.io/ese335/A03.html) |
|11    |8   |04/08|M.   |[Post-hoc test and Two-way ANOVA](https://zhu-group.github.io/ese335/S11.html)              |                    |                                                              |
|12    |8   |04/10|W.   |[Covariance and Pearson correlation test](https://zhu-group.github.io/ese335/S12.html)      |                    |                                                              |
|13    |9   |04/15|M.   |[Non-parametric tests](https://zhu-group.github.io/ese335/S13.html)                         | [RS] p85-102       | [Assignment 04](https://zhu-group.github.io/ese335/A04.html) |
|14    |10  |04/22|M.   |[Simple linear regression (I)](https://zhu-group.github.io/ese335/S14.html)                 | [RS] p176-198      |                                                              |
|15    |10  |04/24|W.   |[Simple linear regression (II)](https://zhu-group.github.io/ese335/S15.html)                | [RS] p207-227      |                                                              |
|16    |11  |04/29|M.   |[Multiple linear regression](https://zhu-group.github.io/ese335/S16.html)                   | [RS] p237-261      | Assignment 05                                                |
|17    |12  |05/06|M.   |[Logistic regression](https://zhu-group.github.io/ese335/S17.html)                          | [RS] p601-622      |                                                              |
|18    |12  |05/08|W.   |[Time series analysis (I)](https://zhu-group.github.io/ese335/S18.html)                     | [SS] p1-33 77-144  |                                                              |
|19    |13  |05/13|M.   |[Time series analysis (II)](https://zhu-group.github.io/ese335/S19.html)                    | [SS] p1-33 77-144  |                                                              |
|-     |14  |05/20|M.   |Course review                                                                               |                    |                                                              |
|-     |14  |05/22|W.   |Course exam                                                                                 |                    |                                                              |
|20    |15  |05/27|M.   |Plotting with `R` (I): `ggplot2`                                                            |                    |                                                              |
|21    |16  |06/03|M.   |Plotting with `R` (II): making maps                                                         |                    |                                                              |  
|22    |16  |06/05|W.   |Making websites with R Markdown                                                             |                    |                                                              |  
|-     |-   |TBD  |-    |Final project presentation (poster)                                                         |                    |                                                              |
