---
title: "Syllabus"
output:
  html_document:
    df_print: paged
---

***

**ESE 335 Environmental Data Analysis**  
Monday 10:20-12:10  
Wednesday (odd week only) 10:20-12:10  
208, Building #2, Li Yuan  
[Schedule for 2022 Spring](https://zhu-group.github.io/ese335/Schedule.html) 

***

**Course Website**  
https://zhu-group.github.io/ese335  

[Tencent class link](https://ke.qq.com/webcourse/4201175/104358997#from=800021724&lite=1&live=1)


**Instructor**  
Lei Zhu  
*School of Environmental Science and Engineering  
Office: 907, CoE North   
Email: zhul3@sustech.edu.cn  
Office Hours: By appointment*

**Teaching Assistant (TA)**  
Xiaoxing Zuo   
*School of Environmental Science and Engineering  
Office: 903B, CoE North   
Email: 12132243@mail.sustech.edu.cn
Office Hours: TBD*

**Credit**   
The course has a credit of 3.0, with a total class hour of 48.

**Course Description**   
As an interdisciplinary field, environmental science gains insights from various data sets of field studies, lab experiments, remote sensing, and model simulations. Analyzing and visualizing data sets has become one of the most critical skills for carrying out environmental studies. However, SUSTech ESE undergraduate students often find their opportunities to access such courses confined, and specific training toward developing desired skills limited. 

This course will teach students how to apply suitable statistical methods and visualization tools to analyze environmental data. Topics include basics of statistics, features of environmental data, checking data sets, comparisons between two groups, comparisons among several groups, correlation tests, simple linear regression, multiple linear regression, logistic regression, and time series analysis. Students will also learn how to conduct data analysis and visualization properly using the `R` language.

**Course Objectives**  
This course will facilitate student learning with pre-class readings, section examples, lectures, in-class exercises, assignments, exam, final project, and one-on-one interactions. At the end of the course, students should be able to analyze and visualize environmental data sets using suitable statistical methods and `R` tools. This course would also boost students’ programming skills, broadly applicable in their later study and research.

**Pre-requisites**  
Statistics or permission of the instructor.

**Textbooks**   

+ **[RS]** Ramsey F. and D. Schafer, *The Statistical Sleuth: A Course in Methods of Data Analysis*, Cengage Learning, 3^rd^ Edition (May 2, 2012), 784 pages, ISBN-10: 1133490670, ISBN-13: 978-1133490678.

+ **[SS]** Shumway R. and D. Stoffer, *Time Series Analysis and Its Applications With R Examples*, Springer, 4^th^ Edition (April 19, 2017), 575 pages, ISBN-10: 3319524518, ISBN-13: 978-3319524511.

+ Other readings will be freely available from online resources and made available through the course website.

**Course Requirements**   

+ Pre-class readings - Students are required to study the assigned readings prior to the class. 

+ Laptop - Bring laptops to the class to learn `R` programming.   

+ In-class exercises - You will be asked to finish 2-3 in-class exercises at the end of each section. 

+ Assignments - Assignments will be posted on this website. Due in class, no late assignments will be accepted.  

+ Exam - The exam will be an in-class test. You will be allowed to bring a two-paged (A4) cheat sheet.

+ Final project - Each student will choose a question/topic of interest to study, make a poster, and present it to the whole class. 

+ Participation - Participation in discussions is encouraged. You are also welcome to Office Hours held by the instructor and TA for specific questions.

**Grading**   

+ Assignments (30%)

+ Exam (30%) 

+ Final project - poster presentation (30%)

+ Class participation (10%)

+ Academic dishonesty - Just don't. If you're not interested in learning and doing the work, don't do it. But, please don't cheat or plagiarize. It's insulting to both you and the instructor and no good comes from it.

**Schedule**

[Schedule for 2022 Spring](https://zhu-group.github.io/ese335/Schedule.html)
